// DO NOT EDIT - generated by github.com/edwarnicke/imports-gen
package imports

import (
	_ "context"
	_ "io/ioutil"
	_ "net"
	_ "net/url"
	_ "os"
	_ "path/filepath"
	_ "time"

	_ "github.com/antonfisher/nested-logrus-formatter"
	_ "github.com/edwarnicke/debug"
	_ "github.com/edwarnicke/grpcfd"
	_ "github.com/edwarnicke/log"
	_ "github.com/edwarnicke/signalctx"
	_ "github.com/edwarnicke/vpphelper"
	_ "github.com/golang/protobuf/ptypes"
	_ "github.com/kelseyhightower/envconfig"
	_ "github.com/sirupsen/logrus"
	_ "github.com/spiffe/go-spiffe/v2/spiffetls/tlsconfig"
	_ "github.com/spiffe/go-spiffe/v2/workloadapi"
	_ "google.golang.org/grpc"
	_ "google.golang.org/grpc/credentials"

	_ "github.com/networkservicemesh/api/pkg/api/registry"
	_ "github.com/networkservicemesh/sdk-vpp/pkg/networkservice/chains/xconnectns"
	_ "github.com/networkservicemesh/sdk/pkg/networkservice/common/authorize"
	_ "github.com/networkservicemesh/sdk/pkg/registry/common/sendfd"
	_ "github.com/networkservicemesh/sdk/pkg/registry/core/chain"
	_ "github.com/networkservicemesh/sdk/pkg/tools/grpcutils"
	_ "github.com/networkservicemesh/sdk/pkg/tools/spiffejwt"
)
